name: Job Scrapper CI

on:
  schedule:
    - cron: 0 */6 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: print working directory
      run: pwd
    - name: ls command
      run: ls
    - name: Build the Docker image
      run: docker build job-scraper/ --tag job-scraper:$(date +%d)
    - name: run the Docker image
      run: docker run job-scraper:$(date +%d)
